In [2]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportions_ztest

In [3]:
df = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_norm.csv')

In [9]:
df.head()

sample
0    74.5
1    81.2
2    73.8
3    82.0
4    76.3

In [14]:
# 정규성 검정
x = stats.shapiro(df)
print('The Shapiro-Willkis Statistic is %.3f and the p-value is %.3f' %x)

# 1-Sample t-test
t_result = stats.ttest_1samp(df,76.7)
t,p = t_result.statistic.round(3), t_result.pvalue.round(3)
print("1-Sample t-test")
print("t검정통계량: {}".format(t))
print("p-value: {}.".format(p))

The Shapiro-Willkis Statistic is 0.933 and the p-value is 0.480
1-Sample t-test
t검정통계량: [0.864]
p-value: [0.41].


In [18]:
df_a = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_sampt1.csv')
df_b = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_sampt2.csv')

# 정규성 검정
x = stats.shapiro(df_a)
print('The Shapiro-Willkis Statistic is %.3f and the p-value is %.3f' %x)
y = stats.shapiro(df_b)
print('The Shapiro-Willkis Statistic is %.3f and the p-value is %.3f' %y)

#  등분산성 검정
stat, p= stats.bartlett(df_a['sample'], df_b['sample'])
print("등분산검정결과 p-value는 %.3f" %p)

# 2-Sample t-test
t_result = stats.ttest_ind(df_a['sample'], df_b['sample'],equal_var = True)
t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("2-Sample t-test")
print("t검정통계량: {}".format(t))
print("p-value: {}".format(p))

The Shapiro-Willkis Statistic is 0.909 and the p-value is 0.062
The Shapiro-Willkis Statistic is 0.898 and the p-value is 0.038
등분산검정결과 p-value는 0.642
2-Sample t-test
t검정통계량: -3.122
p-value: 0.003


In [26]:
df = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_pair.csv')

# 정규성 검정
x = stats.shapiro(df['before'])
print('The Shapiro-Willkis Statistic is %.3f and the p-value is %.3f' %x)
y = stats.shapiro(df['after'])
print('The Shapiro-Willkis Statistic is %.3f and the p-value is %.3f' %y)

#  등분산성 검정
stat, p= stats.bartlett(df['before'], df['after'])
print("등분산검정결과 p-value는 %.3f" %p)

# Paired t-test
t_result = stats.ttest_rel(df['before'], df['after'])

t,p = t_result.statistic.round(3), t_result.pvalue.round(3)

print("Paired t-test")
print("t검정통계량: {}".format(t))
print("p-value: {}".format(p))

The Shapiro-Willkis Statistic is 0.871 and the p-value is 0.104
The Shapiro-Willkis Statistic is 0.837 and the p-value is 0.040
등분산검정결과 p-value는 0.401
Paired t-test
t검정통계량: -5.324
p-value: 0.0


In [30]:
count = 15
nobs = 100
value = .1

# proportion test 실행
stat, pval = proportions_ztest(count,nobs,value)

print("Paired t-test")
print("p검정통계량: {}".format(stat))
print("p-value: {}".format(pval))

Paired t-test
p검정통계량: 1.4002800840280094
p-value: 0.16142946236708322


In [31]:
count = np.array([4,1])
nobs = np.array([1000,1200])

# proportiono test 실행
stat,pval = proportions_ztest(count,nobs)

print("Paired t-test")
print("p검정통계량: {}".format(stat))
print("p-value: {}".format(pval))

Paired t-test
p검정통계량: 1.553109404737079
p-value: 0.12039699966295712


In [32]:
df = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_var.csv')

# 등분산성 검정
stats.bartlett(df['A'],df['B'])

BartlettResult(statistic=0.2158392670118528, pvalue=0.6422286416307027)

In [33]:
df = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_cor.csv')
df.head()

minutes  units
0        1     23
1        2     29
2        3     49
3        4     64
4        4     74

In [36]:
corr, pval = stats.pearsonr(df['minutes'], df['units'])

In [37]:
print('Correlation Analysis')
print("corr: {0: 0.3f}".format(corr))
print("p:{0:0.3f}".format(pval))

Correlation Analysis
corr:  0.989
p:0.000


In [38]:
df = pd.read_csv('C:/Users/black/Downloads/솔트룩스/data/data_chi.csv',encoding = 'euc-kr')

# chi-square test 실행
chi, pval, dof, expected = stats.chi2_contingency(df)

print('Chi-square test')
print("corr: {0: 0.3f}".format(chi))
print("p:{0:0.3f}".format(pval))
print("degree pf freedom: {}".format(dof))
print('expected value: \n{}'.format(expected.round(3)))

Chi-square test
corr:  13.366
p:0.038
degree pf freedom: 6
expected value: 
[[258.333 258.333 258.333]
 [276.333 276.333 276.333]
 [230.667 230.667 230.667]
 [234.667 234.667 234.667]]
